In [26]:
## Importing all the important libraries required for analysis and EDA
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [27]:
df=pd.read_csv("Credit Dataset for HV Turnkey Lender.csv") ## reading the data set 

In [28]:
df.head()

ID       AMT  GENDER  EDUCATION  MARITAL STATUS  AGE  REPAY_SEP  REPAY_AUG  \
0   1   20000.0       2        2.0               1   24          2          2   
1   2  120000.0       2        2.0               2   26          0          2   
2   3   90000.0       2        2.0               2   34          0          0   
3   4   50000.0       2        2.0               1   37          0          0   
4   5   50000.0       1        2.0               1   57          0          0   

   REPAY_JUL  REPAY_JUN  ...  AMTBILL_APR  PRE_SEP  PRE_AUG  PRE_JUL  PRE_JUN  \
0          0          0  ...          0.0      0.0    689.0      0.0      0.0   
1          0          0  ...       3261.0      0.0   1000.0   1000.0   1000.0   
2          0          0  ...      15549.0   1518.0   1500.0   1000.0   1000.0   
3          0          0  ...      29547.0   2000.0   2019.0   1200.0   1100.0   
4          0          0  ...      19131.0   2000.0  36681.0  10000.0   9000.0   

   PRE_MAY  PRE_APR  DEF_AMT  Sum_Column  Sum_PRE_Column  
0      0.0      0.0        1      7704.0           689.0  
1      0.0   2000.0        1     17077.0          5000.0  
2   1000.0   5000.0        0    101653.0         11018.0  
3   1069.0   1000.0        0    231334.0          8388.0  
4    689.0    679.0        0    109339.0         59049.0  

[5 rows x 27 columns]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   ID              30000 non-null  int64  
 1   AMT             30000 non-null  float64
 2   GENDER          30000 non-null  int64  
 3   EDUCATION       29986 non-null  float64
 4   MARITAL STATUS  30000 non-null  int64  
 5   AGE             30000 non-null  int64  
 6   REPAY_SEP       30000 non-null  int64  
 7   REPAY_AUG       30000 non-null  int64  
 8   REPAY_JUL       30000 non-null  int64  
 9   REPAY_JUN       30000 non-null  int64  
 10  REPAY_MAY       30000 non-null  int64  
 11  REPAY_APR       30000 non-null  int64  
 12  AMTBILL_SEP     30000 non-null  float64
 13  AMTBILL_AUG     30000 non-null  float64
 14  AMTBILL_JUL     30000 non-null  float64
 15  AMTBILL_JUN     30000 non-null  float64
 16  AMTBILL_MAY     30000 non-null  float64
 17  AMTBILL_APR     30000 non-null 

In [ ]:
import matplotlib.pyplot as plt

df.hist(figsize=(20,14))
plt.show()

In [24]:
# Calculate the sum of columns 'AMTBILL_SEP', 'AMTBILL_AUG', 'AMTBILL_JUL', 'AMTBILL_JUN', 'AMTBILL_MAY','AMTBILL_APR for each row
df['Sum_Column'] = df[['AMTBILL_SEP', 'AMTBILL_AUG', 'AMTBILL_JUL', 'AMTBILL_JUN', 'AMTBILL_MAY','AMTBILL_APR']].sum(axis=1)

# Save the updated DataFrame to a new Excel file
output_excel_file = 'Credit Dataset for HV Turnkey Lender.csv'  # Replace with your desired output file path
df.to_csv('Credit Dataset for HV Turnkey Lender.csv', index=False)

# Display the updated DataFrame
print(df)


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [25]:
# Calculate the sum of Pre_columns PRE_SEP,'PRE_AUG', 'PRE_JUL', 'PRE_JUN', 'PRE_MAY','PRE_APR for each row
df['Sum_PRE_Column'] = df[['PRE_SEP', 'PRE_AUG', 'PRE_JUL', 'PRE_JUN', 'PRE_MAY','PRE_APR']].sum(axis=1)

# Save the updated DataFrame to a new Excel file
output_excel_file = 'Credit Dataset for HV Turnkey Lender.csv'  # Replace with your desired output file path
df.to_csv('Credit Dataset for HV Turnkey Lender.csv', index=False)

# Display the updated DataFrame
print(df)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [8]:
df.describe()

ID             AMT        GENDER     EDUCATION  \
count  30000.000000    30000.000000  30000.000000  29986.000000   
mean   15000.500000   167484.322667      1.603733      1.852298   
std     8660.398374   129747.661567      0.489129      0.781622   
min        1.000000    10000.000000      1.000000      1.000000   
25%     7500.750000    50000.000000      1.000000      1.000000   
50%    15000.500000   140000.000000      2.000000      2.000000   
75%    22500.250000   240000.000000      2.000000      2.000000   
max    30000.000000  1000000.000000      2.000000      5.000000   

       MARITAL STATUS           AGE     REPAY_SEP     REPAY_AUG     REPAY_JUL  \
count    30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean         1.555567     35.485500      0.356767      0.320033      0.304067   
std          0.518833      9.217904      0.760594      0.801727      0.790589   
min          1.000000     21.000000      0.000000      0.000000      0.000000   
25%          1.000000     28.000000      0.000000      0.000000      0.000000   
50%          2.000000     34.000000      0.000000      0.000000      0.000000   
75%          2.000000     41.000000      0.000000      0.000000      0.000000   
max          3.000000     79.000000      8.000000      8.000000      8.000000   

          REPAY_JUN  ...    AMTBILL_APR        PRE_SEP       PRE_AUG  \
count  30000.000000  ...   30000.000000   30000.000000  3.000000e+04   
mean       0.258767  ...   38907.530300    5663.580500  5.921163e+03   
std        0.761113  ...   59511.193927   16563.280354  2.304087e+04   
min        0.000000  ... -339603.000000       0.000000  0.000000e+00   
25%        0.000000  ...    1261.000000    1000.000000  8.330000e+02   
50%        0.000000  ...   17075.500000    2100.000000  2.009000e+03   
75%        0.000000  ...   49205.250000    5006.000000  5.000000e+03   
max        8.000000  ...  961664.000000  873552.000000  1.684259e+06   

            PRE_JUL        PRE_JUN        PRE_MAY        PRE_APR  \
count   30000.00000   30000.000000   30000.000000   30000.000000   
mean     5225.68150    4826.076867    4799.387633    5215.502567   
std     17606.96147   15666.159744   15278.305679   17777.465775   
min         0.00000       0.000000       0.000000       0.000000   
25%       390.00000     296.000000     252.500000     117.750000   
50%      1800.00000    1500.000000    1500.000000    1500.000000   
75%      4505.00000    4013.250000    4031.500000    4000.000000   
max    896040.00000  621000.000000  426529.000000  528666.000000   

            DEF_AMT    Sum_Column  Sum_PRE_Column  
count  30000.000000  3.000000e+04    3.000000e+04  
mean       0.221200  2.699977e+05    3.165139e+04  
std        0.415062  3.795522e+05    6.082768e+04  
min        0.000000 -3.362590e+05    0.000000e+00  
25%        0.000000  2.886825e+04    6.679750e+03  
50%        0.000000  1.263610e+05    1.438300e+04  
75%        0.000000  3.426265e+05    3.350350e+04  
max        1.000000  5.263883e+06    3.764066e+06  

[8 rows x 27 columns]

In [41]:
import pandas as pd
from scipy import stats
# Column for which you want to calculate the confidence interval
column_name = 'Sum_PRE_Column'

# Extract the column data
data = df[column_name]

TypeError: 'int' object is not subscriptable

In [9]:
X = df[['AMT','AGE','REPAY_SEP','REPAY_AUG',
        'REPAY_JUL','REPAY_JUN','PRE_JUN','PRE_JUL','PRE_MAY','PRE_APR','Sum_Column','Sum_PRE_Column']]
      

In [10]:
pd.get_dummies(X)

AMT  AGE  REPAY_SEP  REPAY_AUG  REPAY_JUL  REPAY_JUN  PRE_JUN  \
0       20000.0   24          2          2          0          0      0.0   
1      120000.0   26          0          2          0          0   1000.0   
2       90000.0   34          0          0          0          0   1000.0   
3       50000.0   37          0          0          0          0   1100.0   
4       50000.0   57          0          0          0          0   9000.0   
...         ...  ...        ...        ...        ...        ...      ...   
29995  220000.0   39          0          0          0          0   3047.0   
29996  150000.0   43          0          0          0          0    129.0   
29997   30000.0   37          4          3          2          0   4200.0   
29998   80000.0   41          1          0          0          0   1926.0   
29999   50000.0   46          0          0          0          0   1000.0   

       PRE_JUL  PRE_MAY  PRE_APR  Sum_Column  Sum_PRE_Column  
0          0.0      0.0      0.0      7704.0           689.0  
1       1000.0      0.0   2000.0     17077.0          5000.0  
2       1000.0   1000.0   5000.0    101653.0         11018.0  
3       1200.0   1069.0   1000.0    231334.0          8388.0  
4      10000.0    689.0    679.0    109339.0         59049.0  
...        ...      ...      ...         ...             ...  
29995   5003.0   5000.0   1000.0    725349.0         42550.0  
29996   8998.0      0.0      0.0     21182.0         14490.0  
29997  22000.0   2000.0   3100.0     70496.0         31300.0  
29998   1178.0  52964.0   1804.0    268901.0        147181.0  
29999   1430.0   1000.0   1000.0    230874.0          8308.0  

[30000 rows x 12 columns]

In [11]:
y=df['DEF_AMT']

In [12]:
from sklearn.preprocessing import LabelEncoder
# Initialising Label encoder
encoder = LabelEncoder()


In [13]:
encoder.fit(y)

LabelEncoder()

In [14]:
encoder.transform(y)

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [15]:
y_encoded = encoder.transform(y)


In [16]:
y_encoded = encoder

In [17]:
encoder.inverse_transform([0])

array([0], dtype=int64)

In [18]:
### Finding the Poisson for the data set 
from scipy.stats import poisson

In [19]:
poisson.cdf(1,1)

0.7357588823428847

In [20]:
np.random.seed(42)
df = np.random.normal(loc=10, scale=2, size=1000)

In [21]:
## Finding the binominial Distribution 
from scipy.stats import binom

In [22]:
binom.pmf(6,16,0,0.24884449755371676)

0.0

In [37]:
# Calculate the mean and standard deviation of the data
mean = data.mean()
std_dev = data.std(ddof=1)

In [38]:
#
 # ddof=1 for sample standard deviation, ddof=0 for population standard deviation

# Set the confidence level (e.g., 95% confidence interval)
confidence_level = 0.95

# Calculate the standard error of the mean
stderr = std_dev / (len(data) ** 0.5)

# Calculate the degrees of freedom
df = len(data) - 1

# Use the t.interval function to calculate the confidence interval
conf_interval = stats.t.interval(confidence_level, df, loc=mean, scale=stderr)

# Display the results
print(f"Mean: {mean}")
print(f"Standard Deviation: {std_dev}")
print(f"Confidence Interval ({confidence_level*100}%): {conf_interval}")

Mean: 0.2212
Standard Deviation: 0.4150618056909671
Confidence Interval (95.0%): (0.21650303031147078, 0.22589696968852924)


In [40]:
## lets conduct the hypothesis testing 
column_name = ' AMTBILL_SEP'

# Extract the column data
data = df[column_name]

# Hypothesized population mean (replace with your specific hypothesis)
hypothesized_mean = 20

# Perform a one-sample t-test
t_stat, p_value = stats.ttest_1samp(data, hypothesized_mean)

# Display the results
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")

# Check if the p-value is less than the significance level (e.g., 0.05)
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

TypeError: 'int' object is not subscriptable

In [42]:
my_dict = {'key': 'value'}
print(my_dict['key'])

value


In [45]:
import pandas as pd
from scipy.stats import chi2_contingency

In [56]:
# Create a contingency table
categorical_columns = ['AMT', 'DEF_AMT']

In [58]:
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

In [59]:
contingency_table = pd.crosstab(df[categorical_columns['AMT']], df[categorical_columns['DEF_AMT'


SyntaxError: unterminated string literal (detected at line 1) (1661483849.py, line 1)

In [52]:
# Perform the chi-square test
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

# Display the results
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(expected)

# Check if the p-value is less than the significance level (e.g., 0.05)
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis, there is a significant association between the variables")
else:
    print("Fail to reject the null hypothesis, no significant association detected")

Chi-square statistic: 0.0
P-value: 1.0
Degrees of freedom: 1
Expected frequencies:
[[2.5 2.5]
 [2.5 2.5]]
Fail to reject the null hypothesis, no significant association detected
